### ISSUE TITLE
Where do you get these access_tokens?

### ISSUE THREAD

**Issue by timqian** [veniversum/git-visualizer#6]
I am building some github api based programs ( [star-history](https://github.com/timqian/star-history) ), and rate limit is a huge problem for me. I find you cleaverly solved the problem by using 6 different access_tokens.

I am wondering where do you get these tokens? Do you just sign up 6 account on github?

**Comment by veniversum** [comment]
You could try caching API results if you have a server side element, or find other ways to reduce number of API calls. Alternatively provide an OAuth login so the user can use their own account instead.

I'm using access tokens generated from my own account, since this application only makes 2 calls per request and should be able to remain under the rate limit.

**Comment by timqian** [comment]
You mean all the tokens are generate by the same account?  I thought github count request number by user. So it's the same as just generate one token. 
The doc is a little confusing. https://developer.github.com/v3/#rate-limiting

**Comment by veniversum** [comment]
Indeed, tokens have to be generated on different accounts in order to have separate rate limits.

**Comment by timqian** [comment]
I thinks so too
